chore: update custom types directory for new sm format
prismicio-community/slice-library-starter-next pull request #5
Opened 2021-06-08 16:06 UTC by MarcMcIntosh

change the custom-types directory for new version of slicemachine, this will require version 4 of the cli (currently in aplha)

2021-06-11 14:32 UTC, hypervillain approved these changes

2021-06-11 14:32 UTC, hypervillain commented on custom_types/page/index.json
> +  "repeatable": true,
It should have an empty "description" and a boolean "status" I believe! See https://documenter.getpostman.com/view/5743666/TzCHBqbH#9d1e3269-ee00-4b7e-94df-a8c092b88f99

2021-06-11 14:32 UTC, hypervillain commented on custom_types/page/index.json
> +      "body": {
Can you rename "body" to "slices"?

2021-06-11 14:37 UTC, hypervillain commented
Also, `custom_types` should be moved to `customtypes`. This also applies here: https://github.com/prismicio-community/nextjs-sm-tutorial-series/pull/3/files and in the Nuxt tutorial I guesss

2021-06-11 14:48 UTC, hypervillain requested changes
We just need to rename the folder and the 2 fields to both cts and it's good to go for me!

2021-07-09 16:25 UTC, closed without merging

2021-07-13 12:31 UTC, MarcMcIntosh commented on custom_types/page/index.json
> +  "repeatable": true,
I'll check 'common.models.masks.Mask#readerForm' and which is use when for creating a repo.

Are these changes going to be consistent across all of prismic?